import{computed,onMounted,onUnmounted,ref}from'vue'
export function useVoice(){const voices=ref([]),voiceURI=ref(localStorage.getItem('nahui-voice')||''),engine=ref('browser'),loading=ref(false),status=ref('');let kokoro=null
const englishVoices=computed(()=>voices.value.filter(v=>/^en[-_]/i.test(v.lang)))
function loadVoices(){voices.value=speechSynthesis.getVoices();if(!voiceURI.value||!voices.value.some(v=>v.voiceURI===voiceURI.value)){const priority=['Microsoft Aria','Microsoft Jenny','Microsoft Guy','Microsoft Sonia','Microsoft Ryan','Google US English','Google UK English'];const hit=priority.map(n=>englishVoices.value.find(v=>v.name.includes(n))).find(Boolean)||englishVoices.value.find(v=>v.lang==='en-US')||englishVoices.value[0];voiceURI.value=hit?.voiceURI||''}}
function chooseAccent(lang){const candidates=englishVoices.value.filter(v=>v.lang.toLowerCase().startsWith(lang.toLowerCase()));const natural=candidates.find(v=>/Natural|Aria|Jenny|Guy|Sonia|Ryan|Google/i.test(v.name))||candidates[0];if(natural){voiceURI.value=natural.voiceURI;localStorage.setItem('nahui-voice',voiceURI.value)}}
async function speakBrowser(text,rate=.92){loadVoices();speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);const v=voices.value.find(x=>x.voiceURI===voiceURI.value);if(v){u.voice=v;u.lang=v.lang}else u.lang='en-US';u.rate=rate;u.pitch=1;status.value=`Reproduciendo: ${v?.name||u.lang}`;u.onend=()=>status.value='';speechSynthesis.speak(u)}
async function speakKokoro(text,accent='us'){try{loading.value=true;status.value='Cargando Kokoro local. La primera vez descarga el modelo...';if(!kokoro){const{KokoroTTS}=await import('kokoro-js');kokoro=await KokoroTTS.from_pretrained('onnx-community/Kokoro-82M-ONNX',{dtype:'q4'})}const voice=accent==='gb'?'bf_emma':'af_heart';const audio=await kokoro.generate(text,{voice});const blob=audio.toBlob?audio.toBlob():new Blob([audio.audio],{type:'audio/wav'});const url=URL.createObjectURL(blob);const player=new Audio(url);status.value=`Kokoro: ${voice}`;await player.play();player.onended=()=>{status.value='';URL.revokeObjectURL(url)}}catch(e){status.value='Kokoro no pudo iniciar; usando voz del sistema.';await speakBrowser(text)}finally{loading.value=false}}
async function speak(text,accent='us',rate=.92){if(engine.value==='kokoro')return speakKokoro(text,accent);return speakBrowser(text,rate)}
onMounted(()=>{loadVoices();speechSynthesis.addEventListener('voiceschanged',loadVoices)});onUnmounted(()=>speechSynthesis.removeEventListener('voiceschanged',loadVoices));return{voices,englishVoices,voiceURI,engine,loading,status,loadVoices,chooseAccent,speak}}
