<script setup>
import {computed,ref,watch} from 'vue';import {readingSets,listeningTemplates,writingPrompts,speakingQuestions} from './data/exercises';import {historyJourneys,historySources} from './data/history';import {useSpeech,useRecorder} from './composables/audio'
const page=ref('home'),mode=ref('practice'),variant=ref(localStorage.getItem('nahui-variant')||'en-US'),scores=ref(JSON.parse(localStorage.getItem('nahui-scores')||'{}'));const selected=ref({}),checked=ref(false),plays=ref(0),draft=ref(localStorage.getItem('nahui-draft')||''),historyIndex=ref(0),speakingIndex=ref(0),followup=ref(''),diagnosticStep=ref(0);const speech=useSpeech(),rec=useRecorder();let currentListening=ref(null)
const words=computed(()=>(draft.value.trim().match(/\b[\w’'-]+\b/g)||[]).length);watch(draft,v=>localStorage.setItem('nahui-draft',v));watch(variant,v=>localStorage.setItem('nahui-variant',v));watch(scores,v=>localStorage.setItem('nahui-scores',JSON.stringify(v)),{deep:true})
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}function go(p){page.value=p;selected.value={};checked.value=false;plays.value=0;if(p==='listening')makeListening();scrollTo(0,0)}
function gradeReading(set){checked.value=true;let good=0;set.questions.forEach((q,i)=>{if(selected.value[i]===q.answer)good++});scores.value.reading=Math.round(good/set.questions.length*100)}
function makeListening(){const base=listeningTemplates[Math.floor(Math.random()*listeningTemplates.length)];const values={};for(const[k,v]of Object.entries(base.variables))values[k]=v[Math.floor(Math.random()*v.length)];let script=base.template.replace(/\{(\w+)\}/g,(_,k)=>values[k]);const qs=base.questions.map(q=>{if(q.fixedOptions)return{...q,options:q.fixedOptions};let correct=values[q.field];let pool=q.optionsFrom.flatMap(k=>base.variables[k]).filter(x=>x!==correct);return{...q,options:shuffle([correct,...shuffle(pool).slice(0,2)]),answer:null,correct}});qs.forEach(q=>{if(q.correct)q.answer=q.options.indexOf(q.correct)});currentListening.value={...base,script,questions:qs}}
function playListening(){if(plays.value>=(mode.value==='exam'?2:99))return;plays.value++;speech.speak(currentListening.value.script,currentListening.value.accent,.9)}function gradeListening(){checked.value=true;let good=0;currentListening.value.questions.forEach((q,i)=>{if(selected.value[i]===q.answer)good++});scores.value.listening=Math.round(good/currentListening.value.questions.length*100)}
function randomHistory(){let n;do{n=Math.floor(Math.random()*historyJourneys.length)}while(n===historyIndex.value&&historyJourneys.length>1);historyIndex.value=n}
function nextSpeaking(){speakingIndex.value=(speakingIndex.value+1)%speakingQuestions.length;followup.value=''}function chooseFollowup(){const f=speakingQuestions[speakingIndex.value].followups;followup.value=f[Math.floor(Math.random()*f.length)];speech.speak(followup.value,variant.value)}
const readiness=computed(()=>{const vals=['reading','listening','writing','speaking'].map(k=>scores.value[k]||0);return Math.round(vals.reduce((a,b)=>a+b,0)/4)})
</script>
<template><a class="skip" href="#main">Saltar al contenido</a><header><button class="brand" @click="go('home')"><b>4</b><span>Nahui Skills <small>BETA 0.5</small></span></button><nav><button v-for="x in [['home','Inicio'],['diagnostic','Diagnóstico'],['reading','Lectura'],['listening','Escucha'],['writing','Escritura'],['speaking','Habla'],['history','English Through Time']]" :class="{active:page===x[0]}" @click="go(x[0])">{{x[1]}}</button></nav></header><main id="main">
<section v-if="page==='home'" class="hero"><div class="wrap"><span class="eyebrow">Operación rescate B2</span><h1>Practica. Detecta.<br>Refuerza.</h1><p>Cuatro habilidades, diagnóstico local y una ruta histórica del inglés con AFI.</p><div class="actions"><button class="cta lime" @click="go('diagnostic')">¿Qué tan preparado estoy?</button><button class="cta white" @click="go('speaking')">Practicar entrevista</button></div></div><i class="bubble b1"></i><i class="bubble b2"></i></section>
<section v-if="page==='home'" class="wrap section"><div class="notice"><b>Preparación estimada:</b> {{readiness}}%. Se calcula con prácticas terminadas y no equivale a certificación oficial.</div><div class="grid"><article v-for="s in [['reading','R','Lectura'],['listening','L','Escucha'],['writing','W','Escritura'],['speaking','S','Habla']]" class="tile"><div class="tile-top"><b class="icon">{{s[1]}}</b><span>{{scores[s[0]]||0}}%</span></div><h2>{{s[2]}}</h2><button class="cta" @click="go(s[0])">Practicar</button></article></div></section>
<section v-else-if="page==='diagnostic'" class="wrap section"><span class="eyebrow">Diagnóstico adaptativo</span><h1>¿Qué necesitas reforzar?</h1><article class="tile exercise"><p>Esta beta combina un reactivo de lectura, uno de escucha y autoevaluaciones breves de producción. El resultado es orientativo.</p><div class="formula">Paso {{diagnosticStep+1}} de 4</div><template v-if="diagnosticStep===0"><p>Completa primero una práctica de lectura.</p><button class="cta" @click="go('reading')">Ir a Lectura</button></template><template v-else-if="diagnosticStep===1"><p>Completa una práctica auditiva.</p><button class="cta" @click="go('listening')">Ir a Escucha</button></template><template v-else-if="diagnosticStep===2"><p>Escribe entre 120 y 140 palabras.</p><button class="cta" @click="go('writing')">Ir a Escritura</button></template><template v-else><p>Graba una respuesta oral.</p><button class="cta" @click="go('speaking')">Ir a Habla</button></template><button class="back" @click="diagnosticStep=(diagnosticStep+1)%4">Siguiente paso</button></article></section>
<section v-else-if="page==='reading'" class="wrap section"><span class="eyebrow">Reading B2</span><h1>Lectura</h1><article class="tile exercise"><h2>{{readingSets[0].title}}</h2><p class="passage">{{readingSets[0].text}}</p><fieldset v-for="(q,i) in readingSets[0].questions" class="question"><legend>{{i+1}}. {{q.prompt}}</legend><label v-for="(o,j) in q.options" class="option"><input v-model="selected[i]" type="radio" :value="j"> {{o}}</label><p v-if="checked" :class="selected[i]===q.answer?'good':'bad'">{{q.why}}</p></fieldset><button class="cta" @click="gradeReading(readingSets[0])">Calificar</button></article></section>
<section v-else-if="page==='listening'" class="wrap section"><span class="eyebrow">Listening dinámico</span><h1>Escucha</h1><article v-if="currentListening" class="tile exercise"><div class="toolbar"><select v-model="mode"><option value="practice">Práctica ilimitada</option><option value="exam">Examen: 2 reproducciones</option></select><span>Reproducciones: {{plays}}{{mode==='exam'?'/2':''}}</span></div><button class="cta" @click="playListening">▶ Reproducir audio</button><fieldset v-for="(q,i) in currentListening.questions" class="question"><legend>{{i+1}}. {{q.prompt}}</legend><label v-for="(o,j) in q.options" class="option"><input v-model="selected[i]" type="radio" :value="j"> {{o}}</label></fieldset><button class="cta" @click="gradeListening">Calificar</button><details v-if="checked"><summary>Ver transcripción</summary><p>{{currentListening.script}}</p></details><button class="back" @click="makeListening();selected={};checked=false;plays=0">Generar otra variante</button></article></section>
<section v-else-if="page==='writing'" class="wrap section"><span class="eyebrow">Writing B2</span><h1>Escritura</h1><article class="tile exercise"><h2>{{writingPrompts[0].genre}}</h2><p>{{writingPrompts[0].prompt}}</p><textarea v-model="draft" placeholder="Write your answer here..."></textarea><p><b>{{words}}</b> palabras. Meta: 120–140.</p><ul><li v-for="p in writingPrompts[0].points">Incluí: {{p}}</li></ul><button class="cta" @click="scores.writing=words>=120&&words<=140?75:40">Guardar autoevaluación</button></article></section>
<section v-else-if="page==='speaking'" class="wrap section"><span class="eyebrow">Entrevista local</span><h1>Habla</h1><article class="tile exercise"><div class="toolbar"><label>Voz <select v-model="variant"><option value="en-US">en-US</option><option value="en-GB">en-GB</option></select></label></div><h2>{{speakingQuestions[speakingIndex].prompt}}</h2><div class="actions"><button class="cta" @click="speech.speak(speakingQuestions[speakingIndex].prompt,variant)">🔊 Escuchar pregunta</button><button class="cta lime" v-if="!rec.recording" @click="rec.start">● Grabar respuesta</button><button class="cta danger" v-else @click="rec.stop">■ Detener</button></div><p v-if="rec.error" class="bad">{{rec.error}}</p><audio v-if="rec.audioUrl" :src="rec.audioUrl" controls></audio><div class="formula">Respuesta → razón → ejemplo → cierre</div><button class="cta white" @click="chooseFollowup">Pregunta de seguimiento aleatoria</button><p v-if="followup"><b>{{followup}}</b></p><button class="back" @click="nextSpeaking">Siguiente pregunta</button><button class="cta" @click="scores.speaking=rec.audioUrl?75:25">Guardar autoevaluación</button></article></section>
<section v-else-if="page==='history'" class="wrap section"><span class="eyebrow">Historia + AFI</span><h1>English Through Time</h1><article class="tile exercise"><div class="toolbar"><span>Frase moderna aleatoria</span><button class="cta" @click="randomHistory">Otra frase</button></div><h2>{{historyJourneys[historyIndex].modern}}</h2><p class="notice">Las adaptaciones pedagógicas y paráfrasis creativas no son testimonios históricos. El asterisco lingüístico se reserva exclusivamente para formas reconstruidas no atestiguadas.</p><div v-for="stage in historyJourneys[historyIndex].stages" class="stage"><div><span class="badge">{{stage.stage}} · {{stage.date}}</span><h3>{{stage.text}}</h3><code>{{stage.ipa}}</code><p>{{stage.note}}</p><small>Estado: {{stage.status}} · Confianza: {{stage.confidence}}</small></div><button class="cta white" @click="speech.speak(stage.text,stage.stage.includes('British')?'en-GB':'en-US',.8)">▶ Voz aproximada</button></div><details><summary>Fuentes académicas del módulo</summary><ul><li v-for="s in historySources"><a :href="s.url" target="_blank" rel="noopener">{{s.citation}}</a></li></ul></details></article></section>
</main><footer>Nahui Skills es independiente y no está afiliado al IPN. Código AGPL-3.0. El procesamiento de voz depende del navegador.</footer></template>
